/**
 * Generate a standalone Lua script for DaVinci Resolve
 * Works with any version - no Python compatibility issues!
 */

interface ImageMapping {
  nr: number;
  timestamp: string;
  filename: string;
  startTime: string;
  endTime: string;
}

interface ScriptSettings {
  fps: number;
  videoTrack: number;
  imageFolder: string;
}

export function generateDaVinciScript(
  mappings: ImageMapping[],
  settings: ScriptSettings
): string {
  // Convert mappings to Lua table syntax
  const luaMappings = mappings.map(m => 
    `    {nr = ${m.nr}, filename = "${m.filename}", startTime = "${m.startTime}", endTime = "${m.endTime}"}`
  ).join(',\n');

  // No need to escape backslashes when using Lua [[...]] strings
  const imageFolder = settings.imageFolder;

  return `--[[
    DaVinci Resolve Image Placement Script (Lua)
    Auto-generated by Image Generator App
    
    INSTRUCTIONS:
    1. Save this file as place_images.lua
    2. Copy to: %APPDATA%\\Blackmagic Design\\DaVinci Resolve\\Support\\Fusion\\Scripts\\Utility\\
    3. In DaVinci Resolve: Workspace → Scripts → Utility → place_images
    
    OR run from the Console (Workspace → Console, select "Lua", paste and run)
]]

print("============================================================")
print("DaVinci Resolve - Image Placement Script")
print("============================================================")
print("")

-- ===================================================================
-- CONFIGURATION
-- ===================================================================

local FPS = ${settings.fps}
local VIDEO_TRACK = ${settings.videoTrack}
local IMAGE_FOLDER = [[${imageFolder}]]

-- ===================================================================
-- IMAGE MAPPINGS
-- ===================================================================

local IMAGES = {
${luaMappings}
}

-- ===================================================================
-- HELPER FUNCTIONS
-- ===================================================================

-- Check if file exists
local function fileExists(path)
    local file = io.open(path, "r")
    if file then
        file:close()
        return true
    end
    return false
end

-- Parse timestamp (MM:SS or HH:MM:SS) to seconds
local function parseTimestamp(timestamp)
    local parts = {}
    for part in string.gmatch(timestamp, "%d+") do
        table.insert(parts, tonumber(part))
    end
    
    if #parts == 2 then
        -- MM:SS
        return parts[1] * 60 + parts[2]
    elseif #parts == 3 then
        -- HH:MM:SS
        return parts[1] * 3600 + parts[2] * 60 + parts[3]
    else
        return 0
    end
end

-- Convert seconds to frames
local function secondsToFrames(seconds, fps)
    return math.floor(seconds * fps)
end

-- ===================================================================
-- MAIN SCRIPT
-- ===================================================================

-- Step 1: Connect to DaVinci Resolve
print("[1/5] Connecting to DaVinci Resolve...")
local resolve = Resolve() or app:GetResolve()

if not resolve then
    print("  ✗ ERROR: Could not connect to DaVinci Resolve")
    print("")
    print("  Make sure:")
    print("  1. DaVinci Resolve is running")
    print("  2. External scripting is enabled:")
    print("     Settings → System → General → External scripting → Local")
    print("")
    return
end

print("  ✓ Connected!")

-- Step 2: Get current project and timeline
print("")
print("[2/5] Getting current project and timeline...")
local projectManager = resolve:GetProjectManager()
local project = projectManager:GetCurrentProject()

if not project then
    print("  ✗ ERROR: No project is open")
    print("  Please open a project first")
    return
end

print("  ✓ Project: " .. project:GetName())

local timeline = project:GetCurrentTimeline()
if not timeline then
    print("  ✗ ERROR: No timeline is open")
    print("  Please open a timeline first")
    return
end

print("  ✓ Timeline: " .. timeline:GetName())
print("  ✓ FPS: " .. FPS)

-- Step 3: Import images
print("")
print("[3/5] Importing " .. #IMAGES .. " images...")

local mediaPool = project:GetMediaPool()
local rootFolder = mediaPool:GetRootFolder()

-- Create folder for imported images
mediaPool:SetCurrentFolder(rootFolder)
local importFolder = mediaPool:AddSubFolder(rootFolder, "Imported Images")
if importFolder then
    mediaPool:SetCurrentFolder(importFolder)
end

-- Use MediaStorage to get all files from the folder
print("  Scanning folder for images...")
local mediaStorage = resolve:GetMediaStorage()
local allFiles = mediaStorage:GetFileList(IMAGE_FOLDER)

if not allFiles or #allFiles == 0 then
    print("  ✗ ERROR: No files found in folder!")
    print("")
    print("  Check that IMAGE_FOLDER is correct:")
    print("  " .. IMAGE_FOLDER)
    print("")
    print("  Make sure the path is complete and folder exists.")
    return
end

print("  Found " .. #allFiles .. " files in folder")

-- Filter for image files that match our NR patterns
local imagePaths = {}
local expectedNRs = {}

-- Build list of expected NR prefixes
for _, img in ipairs(IMAGES) do
    local prefix = string.format("%03d", img.nr)
    expectedNRs[prefix] = true
end

-- Find matching images
for _, filepath in ipairs(allFiles) do
    -- Extract filename from path
    local filename = filepath:match("([^\\\\]+)$")
    
    -- Check if filename starts with any of our expected NR prefixes
    if filename then
        local prefix = filename:sub(1, 3)
        if expectedNRs[prefix] then
            table.insert(imagePaths, filepath)
        end
    end
end

if #imagePaths == 0 then
    print("  ✗ ERROR: No matching images found!")
    print("")
    print("  Looking for images like: 001_*.jpg, 002_*.png, etc.")
    print("  Found " .. #allFiles .. " files but none match the NR pattern")
    print("")
    print("  First few files in folder:")
    for i = 1, math.min(5, #allFiles) do
        local filename = allFiles[i]:match("([^\\\\]+)$")
        print("    " .. (filename or allFiles[i]))
    end
    return
end

print("  ✓ Found " .. #imagePaths .. " matching images")

-- Import all matching images at once
local importedClips = mediaStorage:AddItemListToMediaPool(imagePaths)

if not importedClips or #importedClips == 0 then
    print("  ✗ ERROR: Failed to import images")
    return
end

print("  ✓ Imported " .. #importedClips .. " images")

-- Create lookup table of imported clips by NR
local clipsByNR = {}
for _, img in ipairs(IMAGES) do
    for _, clip in ipairs(importedClips) do
        local clipName = clip:GetName()
        local expectedPrefix = string.format("%03d", img.nr)
        
        -- Match by NR prefix
        if string.sub(clipName, 1, 3) == expectedPrefix then
            clipsByNR[img.nr] = clip
            break
        end
    end
end

-- Step 4: Create MARKERS on timeline for easy placement
print("")
print("[4/5] Creating markers on timeline...")
print("")

local placed = 0
local failed = 0
local markerColors = {"Blue", "Cyan", "Green", "Yellow", "Red", "Pink", "Purple", "Fuchsia", "Rose", "Lavender", "Sky", "Mint"}

for _, img in ipairs(IMAGES) do
    if clipsByNR[img.nr] then
        local startFrame = secondsToFrames(parseTimestamp(img.startTime), FPS)
        local endFrame = secondsToFrames(parseTimestamp(img.endTime), FPS)
        local duration = endFrame - startFrame
        
        local markerName = string.format("%03d", img.nr)
        local markerNote = string.format("Image %03d goes here - Duration: %d frames", img.nr, duration)
        local color = markerColors[(img.nr % #markerColors) + 1]
        
        local success = timeline:AddMarker(startFrame, color, markerName, markerNote, duration)
        
        if success then
            print("  ✓ Marker #" .. markerName .. " at frame " .. startFrame .. " (" .. img.startTime .. "-" .. img.endTime .. ")")
            placed = placed + 1
        else
            print("  ✗ Failed to create marker for #" .. markerName)
            failed = failed + 1
        end
    end
end

-- Step 5: Summary and Instructions
print("")
print("============================================================")
print("[5/5] Summary")
print("============================================================")
print("Total images: " .. #IMAGES)
print("Imported to Media Pool: " .. #importedClips)
print("Markers created on timeline: " .. placed)
print("============================================================")
print("")
print("✅ DONE! Now complete these easy steps:")
print("")
print("1. Look at your TIMELINE - you'll see colored MARKERS")
print("2. Each marker shows where an image goes (hover to see image #)")
print("3. Open MEDIA POOL → Find 'Imported Images' folder")
print("4. DRAG each image (001, 002, etc.) to its matching marker")
print("")
print("💡 TIP: Match the image number to the marker name!")
print("   Example: Drag '001_hash.jpeg' to the marker labeled '001'")
print("")
print("============================================================")
print("This is MUCH faster than placing 28 clips manually!")
print("============================================================")
`;
}

export function downloadScript(script: string, filename: string = 'place_images.lua') {
  const blob = new Blob([script], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
